/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'unplugin-vue-router/types'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/[...path]': RouteRecordInfo<'/[...path]', '/:path(.*)', { path: ParamValue<true> }, { path: ParamValue<false> }>,
    '/404': RouteRecordInfo<'/404', '/404', Record<never, never>, Record<never, never>>,
    '/about/': RouteRecordInfo<'/about/', '/about', Record<never, never>, Record<never, never>>,
    '/about/site': RouteRecordInfo<'/about/site', '/about/site', Record<never, never>, Record<never, never>>,
    '/archives/': RouteRecordInfo<'/archives/', '/archives', Record<never, never>, Record<never, never>>,
    '/categories/': RouteRecordInfo<'/categories/', '/categories', Record<never, never>, Record<never, never>>,
    '/links/': RouteRecordInfo<'/links/', '/links', Record<never, never>, Record<never, never>>,
    '/page/[page]': RouteRecordInfo<'/page/[page]', '/page/:page', { page: ParamValue<true> }, { page: ParamValue<false> }>,
    '/posts/Butterfly的魔改教程：个性定位信息': RouteRecordInfo<'/posts/Butterfly的魔改教程：个性定位信息', '/posts/Butterfly的魔改教程：个性定位信息', Record<never, never>, Record<never, never>>,
    '/posts/hello-valaxy': RouteRecordInfo<'/posts/hello-valaxy', '/posts/hello-valaxy', Record<never, never>, Record<never, never>>,
    '/posts/Solitude主题使用：推荐插件': RouteRecordInfo<'/posts/Solitude主题使用：推荐插件', '/posts/Solitude主题使用：推荐插件', Record<never, never>, Record<never, never>>,
    '/posts/Solitude主题使用：数学公式': RouteRecordInfo<'/posts/Solitude主题使用：数学公式', '/posts/Solitude主题使用：数学公式', Record<never, never>, Record<never, never>>,
    '/posts/一键激活Windows-office': RouteRecordInfo<'/posts/一键激活Windows-office', '/posts/一键激活Windows-office', Record<never, never>, Record<never, never>>,
    '/posts/为你的网站添加一个监控': RouteRecordInfo<'/posts/为你的网站添加一个监控', '/posts/为你的网站添加一个监控', Record<never, never>, Record<never, never>>,
    '/posts/判断网站CDN是否生效': RouteRecordInfo<'/posts/判断网站CDN是否生效', '/posts/判断网站CDN是否生效', Record<never, never>, Record<never, never>>,
    '/posts/美区id注册教程': RouteRecordInfo<'/posts/美区id注册教程', '/posts/美区id注册教程', Record<never, never>, Record<never, never>>,
    '/posts/部署雷池waf防护自己的网站': RouteRecordInfo<'/posts/部署雷池waf防护自己的网站', '/posts/部署雷池waf防护自己的网站', Record<never, never>, Record<never, never>>,
    '/tags/': RouteRecordInfo<'/tags/', '/tags', Record<never, never>, Record<never, never>>,
  }
}
